config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    # NOTE: We want to redirect users to www as the canonical URL in production
    # If you want to test this, you can make hosts entries like:
    # 127.0.0.1       localhost localhost.com www.localhost.com
    # and remove the production conditional
    constraints subdomain: false do
      get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
    end
  end

  resources :meetup_events
  resources :jassets,path: :resources
  get 'market-resources' => redirect('resources')

  get :import,to: 'jobs#index',as: :import

  get 'contact-us',to: 'contact#index',as: 'contact_us'

  # resources :articles
  resources :blogs, path: 'articles'
  get 'blog' => redirect('articles')
  get 'category/blog' => redirect('articles')
  get 'blog/*path' => redirect('articles')

  resources :syndications, path: 'track-record'

  get 'api/v1/map.png',to: 'map#index',as: 'map'
  get 'api/v1/map.js',to: 'map#js',as: 'js'
  get '/thank-you',to: 'home#thank_you',as: 'after_contact'

  # ARTICLE LINKS
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  link = 'Our Difference'
  get link.parameterize, to: 'articles#our_difference', as: link.parameterize.underscore

  link = 'FAQ'
  get link.parameterize, to: 'articles#faq', as: link.parameterize.underscore
  get 'faqs' => redirect('faq')

  link = 'Financing Investments'
  get link.parameterize, to: 'articles#financing_investments', as: link.parameterize.underscore

  link = 'Property Management'
  get link.parameterize, to: 'articles#property_management', as: link.parameterize.underscore

  link = 'Market & City Reports'
  get link.parameterize, to: 'articles#market_and_city_reports', as: link.parameterize.underscore
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:

  namespace :api do
    namespace :v1 do

      resources :links
      resources :charts
      resources :jassets

      resources :properties do

        collection do

          put :order,to: 'properties#order'

        end

      end

      resources :testimonies do

        collection do

          put :order,to: 'testimonies#order'

        end

      end

    end
  end

  get 'connect_with_meetup', to: 'events#connect_with_meetup', as: :connect_with_meetup
  get '/oauth2/meetup_api', to: 'oauth2#meetup_api'
  get 'properties-search-results' => redirect('properties')
  get 'my-properties' => redirect('properties')
  get 'MyListings' => redirect('properties')
  get 'PropertyDetails' => redirect('properties')

  post 'api/v1/zendesk/ticket',to: 'zendesk#ticket'
  get 'api/v1/zendesk/articles',to: 'zendesk#articles'

  resources :sessions,path: 'access/normal'
  get 'access/normal',to: 'sessions#index',as: 'login'
  get 'access/logout',to: 'sessions#destroy',as: 'logout'

  resources :users,path: 'our-team'
  put 'api/v1/users/order',to: 'users#order'
  post 'api/v1/mailchimp/signup',to: 'mailchimp#signup'
  post 'api/v1/mailchimp/zendesk',to: 'mailchimp#zendesk'

  resources :events, only: :index
  get 'api/v1/meetup',to: 'events#meetup'
  get 'presentations' => redirect('events')
  get 'wipevents' => redirect('events')
  get 'Dallaspresentation' => redirect('events')
  get 'events/*path' => redirect('events')
  get 'more_events' => 'events#more_events'

  get 'angular',to: 'angular#index'

  get 'youtube',to: 'youtube#index',as: 'youtube'
  get 'youtube/:id',to: 'youtube#show'
  get 'play_video/:videoId' => 'youtube#play_video', as: 'play_video'

  get 'radio-show',to: 'radio_show#index',as: 'radio_show'
  get 'real-estate-radio-live' => redirect('radio-show')
  put 'radio-show',to: 'radio_show#update'

  resources :images
  resources :properties do

    resources :images
    collection do
      get 'get_cities'
      post :import

    end

  end

  root 'home#index'
  get 'cn', to: redirect('http://tomwilsonproperties.sfchinesemedia.com', status: 301)

  if Rails.env.production?
    get '404',to: 'application#page_not_found'
    get '422',to: 'application#change_rejected'
    get '500',to: 'application#server_error'
  end
  get '/sitemap.xml', to: redirect('http://res.cloudinary.com/wilsoninvestments/raw/upload/v1494498777/sitemap.xml', status: 301)
  get '*path' => redirect('/')
end

app/models/syndication.rb
class Syndication < ActiveRecord::Base
  mount_uploader :image, SyndicationUploader
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :annual_returns, dependent: :destroy
  accepts_nested_attributes_for :annual_returns, reject_if: :all_blank, allow_destroy: true

  before_save :unique_year

  scope :all_syndications, -> { all.order('close_date DESC') }
  scope :active_syndications, -> { all_syndications.where(active: true) }

  validates_presence_of :title, :purchase_price
  validates :purchase_price, :raise_amount, :price_per_share, :loan_amount, :building_size,
    :lot_size, :number_of_buildings, :number_of_tenants, numericality: { greater_than_or_equal_to: 0, allow_blank: true }, length: { maximum: 10,
    too_long: '%{count} digits is the maximum allowed' }

  STATUS_OPTIONS = [
    ['Select Status',nil],
    ['Sold',:sold],
    ['Currently Held',:currently_held],
    ['Active',:active],
  ]

  def unique_year
    years = annual_returns.map(&:year)
    if years.count != years.uniq.count
      errors.add(:base, 'Annual Report Year Should Be Unique')
      false
    end
  end

  def self.by_user(user)
    user ? all_syndications : active_syndications
  end

  def raw_status
    self.status.present? ? self.status.humanize.cap_each : nil
  end
end

app/controllers/syndications_controller.rb
class SyndicationsController < ApplicationController
  before_action :authorize, except: [:index,:show]
  before_action :set_syndication, only: [:show, :edit, :update, :destroy]

  def index
    @syndications = Syndication.where(status: ['active', 'currently_held', 'sold']).order(:status).by_user(current_user).page(params[:page]).per(Settings.pagination.syndication.per_page)
  end

  def new
    @syndication = Syndication.new
    @syndication.annual_returns.build
  end

  def create
    close_date = Date.strptime(params[:syndication][:close_date], '%m/%d/%Y').to_date if params[:syndication][:close_date].present?
    exit_date = Date.strptime(params[:syndication][:exit_date], '%m/%d/%Y').to_date if params[:syndication][:exit_date].present?
    @syndication = Syndication.new(syndication_params.merge!(close_date: close_date, exit_date: exit_date))
    if @syndication.save
      redirect_to syndications_path, flash: {success: "#{@syndication.title} was successfully created!"}
    else
      render :new
    end
  end

  def show
    @syndication_years = @syndication.annual_returns.pluck(:year).uniq.sort.reverse
    @annual_return = @syndication.annual_returns.by_latest_year
    @annual_return = @syndication.annual_returns.by_year(params[:year]) if params[:year].present?
  end

  def edit
  end

  def update
    close_date = Date.strptime(params[:syndication][:close_date], '%m/%d/%Y').to_date if params[:syndication][:close_date].present?
    exit_date = Date.strptime(params[:syndication][:exit_date], '%m/%d/%Y').to_date if params[:syndication][:exit_date].present?
    if @syndication.update(syndication_params.merge!(close_date: close_date,exit_date: exit_date))
      redirect_to syndications_path, flash: {success: "#{@syndication.title} was successfully updated!"}
    else
      render :edit
    end
  end

  def destroy
    @syndication.destroy
    redirect_to syndications_path, flash: {danger: "#{@syndication.title} was successfully deleted."}
  end

  private

  def set_syndication
    @syndication = Syndication.where(slug: params[:id]).first
    redirect_to syndications_path, flash: {danger: "Track Record '#{params[:id]}' not found"} if @syndication.nil?
  end

  def syndication_params
    params.require(:syndication).permit(:title, :status, :purchase_price, :raise_amount, :hold_period,
    :preferred_return, :average_annual_return, :irr, :price_per_share, :loan_amount,
    :loan_rate, :year_built, :building_size, :lot_size, :number_of_buildings, :property_type, :number_of_tenants, :actual_average_annual_return, :actual_irr, :actual_hold_period,
    :image, :notes, :location, :active, annual_returns_attributes: [:year, :projected_annual_return, :actual_annual_return,
    :quarter_1, :quarter_2, :quarter_3, :quarter_4, :id, :_destroy])
  end
end

app/helpers/syndications_helper.rb
module SyndicationsHelper
  def quarterly_price(quarter)
    quarter.present? ? raw_price(quarter) : '-' 
  end

  def track_record_status_color(status)
    case status
      when 'sold'
        'red'
      when 'currently_held'
        'yellow'
      when 'active'
       'green' 
    end
  end
end

app/views/syndications/_annual_return_detail.html.erb
<% annual_return.each do |annual_return| %>
  <% if annual_return.projected_annual_return.present? || annual_return.actual_annual_return.present? %>
    <div class="notes-term"><span class="text-red">*</span> on $100,000 investment</div>
  <% end %>
  <% if annual_return.projected_annual_return.present? %>
    <li><span class="left"><b>Projected Annual Return*:</b></span><span class="right"><%= raw_price(annual_return.projected_annual_return) %></span></li>
  <% end %>
  <% if annual_return.actual_annual_return.present? %>
    <li><span class="left"><b>Annual Disbursements Paid*:</b></span> <span class="right"><%= raw_price(annual_return.actual_annual_return) %></span></li>
  <% end %>
  <% if annual_return.quarter_1.present? || annual_return.quarter_2.present? || annual_return.quarter_3.present? || annual_return.quarter_4.present? %>
    <li><span class="left"><b>Quarterly Dividend Amount*:</b></span> <span class="right"><%= annual_return.year %></span>
      <ul class="qtr-data">
        <% if annual_return.quarter_1.to_i > 0 %><li class="q1"><b>Q1</b><%= quarterly_price(annual_return.quarter_1) %></li><% end %>
        <% if annual_return.quarter_2.to_i > 0 %><li class="q2"><b>Q2</b><%= quarterly_price(annual_return.quarter_2) %></li><% end %>
        <% if annual_return.quarter_3.to_i > 0 %><li class="q3"><b>Q3</b><%= quarterly_price(annual_return.quarter_3) %></li><% end %>
        <% if annual_return.quarter_4.to_i > 0 %><li class="q4"><b>Q4</b> <%= quarterly_price(annual_return.quarter_4) %></li><% end %>
      </ul>
      <span class="text"><%= '# Q1 was prorated preferred returns based on closing.' if annual_return.quarter_1.to_i > 0 %></span>
    </li>
  <% end %>
<% end %>

app/views/syndications/_annual_return_fields.html.erb
<div class="clearfix"></div>
<div class="new_annual_return">
  <div class="year-value-fields mar-top-15">
    <div class="col-md-3 col-sm-12 col-xs-12">
      <div class="form-group">
        <%= f.label :year, class: 'control-label' %>
        <%= f.number_field :year, min: 0, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-3 col-sm-12 col-xs-12">
      <div class="form-group">
        <%= f.label :projected_annual_return, 'Projected Annual Return', class: 'control-label' %>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <%= f.number_field :projected_annual_return, min: 0, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12 col-xs-12">
      <div class="form-group">
        <%= f.label :actual_annual_return, 'Annual Disbursements Paid', class: 'control-label' %>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <%= f.number_field :actual_annual_return, min: 0, class: 'form-control' %>
        </div>
      </div>
      <div class="row qtr-fields">
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :quarter_1, 'Q1 ($)', class: 'control-label' %>
            <%= f.number_field :quarter_1, min: 0, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :quarter_2, 'Q2 ($)', class: 'control-label' %>
            <%= f.number_field :quarter_2, min: 0, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :quarter_3, 'Q3 ($)', class: 'control-label' %>
            <%= f.number_field :quarter_3, min: 0, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :quarter_4, 'Q4 ($)', class: 'control-label' %>
            <%= f.number_field :quarter_4, min: 0, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-sm-12 col-xs-12 del-link"><%= link_to_remove_association 'Delete', f, { wrapper_class: 'new_annual_return', class: 'btn btn-danger common' } %></div>
    <div class="col-xs-12"><hr></div>
  </div>
</div>

app/views/syndications/_form.html.erb
<%= render 'layouts/jumbtron' %>
<section class="main-body without-search-feature gray-bg">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="box-shadow">
          <ol class="breadcrumb white">
            <li><%= link_to 'Home', root_url %></li>
            <li><%= link_to t('seo.syndication.index.title'), syndications_path %></li>
            <li class="active"><%= action_name.capitalize%></li>
          </ol>
        </div> 
      </div>
    </div>
    <div class="fixed-admin-body">
      <div class="col-xs-12">
        <h1><%= yield(:page_title) %></h1>
        <%= form_for @syndication do |f| %>
        <% if @syndication.errors.any? %>
        <div class="alert alert-danger fade in alert-dismissable">
          <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
          <uib-alert type="danger">
            <ul>
              <% @syndication.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </uib-alert>
        </div>
        <% end %>
        <div class="row mar-top-15">
          <%= render partial: 'syndication_fields', locals: {f: f} %>
          <%= f.fields_for :annual_returns do |ff| %>
          <%= render partial: 'annual_return_fields', locals: {f: ff} %>
          <% end %>
          <div class="col-xs-12 links text-right">
            <%= link_to_add_association 'Add Year Data', f, :annual_returns, class: 'btn blue-btn common' %>
          </div>
          <div class="col-xs-12">
            <%= button_tag(type: 'submit', class: 'btn blue-btn btn-lg mar-btm-30') do %><i class="fa fa-check" aria-hidden="true"></i> Submit<% end %>
            <% if !@syndication.new_record? %>
            <%= link_to syndication_path(@syndication), method: :delete, class: 'btn btn-danger btn-lg mar-btm-30', data: {confirm: 'Are you sure you want to delete this syndication?'} do %><i class="fa fa-times" aria-hidden="true"></i> Delete<% end %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/syndications/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content report-card">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <div class="listing-box">
      <div class="img-box"><%= image_tag syndication.image.thumb.url, alt: '', class: 'img-responsive' %>
        <% if syndication.status.present? %><span class="status-tag top-setting <%= track_record_status_color(syndication.status) %>"><%= syndication.raw_status %></span><% end %>
      </div>
      <h3><%= syndication.title %></h3>
      <ul class="list-unstyled">
        <% if @syndication_years.present? %>
        <li class="dropdown-row">
          <span class="left drop-label"><b>Data by Year:</b></span>
          <span class="right">
            <%= hidden_field_tag 'slug_id', syndication.slug %>
            <%= select_tag 'syndication_years', options_for_select(@syndication_years, @syndication_years.first), {class: 'selectpicker'} %>
          </span>
        </li>
        <% end %>
        <div id='annual_return_detail'></div>
        <div class="row two-col-list">
          <div class="col-sm-6 col-xs-12">
            <h4>Financial Data</h4>
            <dl>
              <dt>Close Date:</dt>
              <dd><%= syndication.close_date.present? ? syndication.close_date.strftime('%d %b %Y') : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Exit Date:</dt>
              <dd><%= syndication.exit_date.present? ? syndication.exit_date.strftime('%d %b %Y') : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Purchase Price + Cap Ex:</dt>
              <dd><%= syndication.purchase_price.present? ? raw_price(syndication.purchase_price) : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Raise Amount:</dt>
              <dd><%= syndication.raise_amount.present? ? raw_price(syndication.raise_amount) : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Minimum Investment:</dt>
              <dd><%= syndication.price_per_share.present? ? raw_price(syndication.price_per_share) : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Projected Hold Period:</dt>
              <dd><%= syndication.hold_period.present? ? syndication.hold_period : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Actual Hold Period:</dt>
              <dd><%= syndication.actual_hold_period.present? ? syndication.actual_hold_period : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Preferred return:</dt>
              <dd><%= syndication.preferred_return.present? ? "#{syndication.preferred_return} %" : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Projected Avg Annual Return:</dt>
              <dd><%= syndication.average_annual_return.present? ? "#{syndication.average_annual_return} %" : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Actual Avg Annual Return:</dt>
              <dd><%= syndication.actual_average_annual_return.present? ? "#{syndication.actual_average_annual_return} %" : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Projected IRR:</dt>
              <dd><%= syndication.irr.present? ? "#{syndication.irr} %" : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Actual IRR:</dt>
              <dd><%= syndication.actual_irr.present? ? "#{syndication.actual_irr} %" : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Loan Amount:</dt>
              <dd><%= syndication.loan_amount.present? ? raw_price(syndication.loan_amount) : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Loan Rate:</dt>
              <dd><%= syndication.loan_rate.present? ? "#{syndication.loan_rate} %" : 'N/A' %></dd>
            </dl>
          </div>
          <div class="col-sm-6 col-xs-12">
            <h4>Property Facts</h4>
            <dl>
              <dt>Property Type:</dt>
              <dd><%= syndication.property_type.present? ? syndication.property_type : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Year Built:</dt>
              <dd><%= syndication.year_built.present? ? syndication.year_built : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Building Size:</dt>
              <dd><% if syndication.building_size.present? %><%= number_with_precision(syndication.building_size, precision: 0, delimiter: ',') %><sup> Sqft</sup><% else %>N/A<% end %></dd>
            </dl>
            <dl>
              <dt>Lot Size:</dt>
              <dd><%= syndication.lot_size.present? ? "#{number_with_precision(syndication.lot_size, precision: 0, delimiter: ',')} Acres" : 'N/A' %></span></dd>
            </dl>
            <dl>
              <dt>Number Of Buildings:</dt>
              <dd><%= syndication.number_of_buildings.present? ? syndication.number_of_buildings : 'N/A' %></dd>
            </dl>
            <dl>
              <dt>Number Of Tenants:</dt>
              <dd><%= syndication.number_of_tenants.present? ? syndication.number_of_tenants : 'N/A' %></dd>
            </dl>
          </div>
        </div>
        <% if @syndication.notes.present? %>
          <li class="notes-text">
            <span class="title">Notes:</span>
            <span class="text"><%= raw("#{syndication.notes}") %></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/syndications/_syndications.html.erb
<% syndications.each do |syndication| %>
<div class="col-md-4 col-sm-6 col-xs-12">
  <div class="listing-box">
    <div class="img-box"><%= image_tag 'loading.svg', 'data-src': syndication.image.thumb.url, alt: '', class: 'img-responsive' %>
      <% if syndication.status.present? %><span class="status-tag top-setting <%= track_record_status_color(syndication.status) %>"><%= syndication.raw_status %></span><% end %>
    </div>
    <h3><%= link_to syndication.title.truncate(Settings.truncate.syndication.title), javascript_void, value: syndication.slug, class: 'open_track_record', id: 'syndication_title' %></h3>
    <ul class="list-unstyled">
      <% if syndication.close_date.present? %><li><span class="left"><b>Close Date:</b></span><span class="right"><%= syndication.close_date.strftime('%d %b %Y') %></span></li><% end %>
      <% if syndication.purchase_price.present? %><li><span class="left"><b>Purchase Price + Cap Ex:</b></span><span class="right"><%= raw_price(syndication.purchase_price) %></span></li><% end %>
      <% if syndication.raise_amount.present? %><li><span class="left"><b>Raise Amount:</b></span><span class="right"><%= raw_price(syndication.raise_amount) %></span></li><% end %>
      <% if syndication.location.present? %><li><b>Location:</b> <%= syndication.location %></li><% end %>
    </ul>
    <div class="button-links-row">
    <%= link_to 'Financial Details', javascript_void, value: syndication.slug, class: 'open_track_record btn border-btn', id: 'learn_more' %>
    <% if current_user %>
      <%= link_to 'Edit', edit_syndication_path(syndication), class: 'btn border-btn' %>
    <% end %>
    </div> 
  </div>
</div>
<% end %>
<div id="report-card-details" class="modal fade" role="dialog"></div>

app/views/syndications/edit.html.erb
<% set_meta_tags title: t('seo.syndication.edit') %>
<%= content_for :page_title, "Editing: #{@syndication.title}" %>
<%= render 'form' %>

app/views/syndications/index.html.erb
<% set_meta_tags(title: "#{t('seo.syndication.index.title')} - #{t('seo.site_title')}", description: t('seo.syndication.index.description'), image: asset_url(t('seo.image_2')), twitter: {image: asset_url(t('seo.image_2'))}, og: {image: asset_url(t('seo.image_2'))}) %>
<%= render 'layouts/jumbtron' %>
<section class="main-body without-search-feature pad-btm-55">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="box-shadow">
          <ol class="breadcrumb">
            <li><%= link_to 'Home', root_url %></li>
            <li class="active"><%= t('seo.syndication.index.title') %></li>
            <% if current_user %>
            <li><%= link_to 'New', new_syndication_path %></li>
            <% end %>
          </ol>
        </div>
        <h1 class="common-title mar-btm-20"><%= t('seo.syndication.index.title') %></h1>
        <div class="list-selection">
          <ul class="list-unstyled" id="building_type_menu">
              <li class="active" building_type="single_family,duplex,fourplex,multifamily,commercial,townhouse" class=""><a href="javascript:;">Syndications</a></li>
              <!-- <li><a href="<%#=properties_path%>">Rental Homes</a></li> -->
          </ul>
        </div>


        <div class="row report-card" id="syndication-listing">
          <% if @syndications.any? %>
            <%= render partial: 'syndications', locals: {syndications: @syndications} %>
          <% else %>
            <div class="col-xs-12 msg-content text-center">
              <h3>No Track Record found</h3>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% if @syndications.any? %>
    <div class="row">
      <div class="col-xs-12 text-center">
        <% if @syndications.current_page < @syndications.num_pages %>
        <%= link_to syndications_path, id: 'more_syndication', class: 'btn btn-lg border-btn space-setting', remote: true do %><i class="fa fa-th" aria-hidden="true"></i> View More
        <% end %>
        <%  end %>
      </div>
    </div>
    <%= paginate @syndications %>
    <% end %>
  </div>
</section>

app/views/syndications/index.js.erb
<% if params[:page].present? %>
  $('#syndication-listing').append("<%= escape_javascript(render partial: 'syndications', locals: { syndications: @syndications } ) %>");
  $('img').unveil();
  $('#syndication_years').selectpicker();
  Syndication.disableMouseClick();
  $('.pagination').replaceWith('<%= escape_javascript paginate(@syndications, remote: true) %>');
  <% if @syndications.current_page == @syndications.num_pages %>
    $('#more_syndication').hide();
  <% end %>
<% end %>

app/views/syndications/new.html.erb
<% set_meta_tags title: t('seo.syndication.new') %>
<%= content_for :page_title, 'New Track Record' %>
<%= render 'form' %>

app/views/syndications/show.js.erb
<% if params[:year].present? %>
  $('#annual_return_detail').html("<%= escape_javascript(render partial: 'annual_return_detail', locals: {annual_return: @annual_return}) %>");
<% else %>
  $('#report-card-details').html("<%= escape_javascript(render partial: 'show', locals: {syndication: @syndication}) %>");
  $('#annual_return_detail').html("<%= escape_javascript(render partial: 'annual_return_detail', locals: {annual_return: @annual_return}) %>");
  $('#report-card-details').modal('show');
<% end %>
$('#syndication_years').selectpicker();
Syndication.databyYear();