config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    # NOTE: We want to redirect users to www as the canonical URL in production
    # If you want to test this, you can make hosts entries like:
    # 127.0.0.1       localhost localhost.com www.localhost.com
    # and remove the production conditional
    constraints subdomain: false do
      get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
    end
  end

  resources :meetup_events
  resources :jassets,path: :resources
  get 'market-resources' => redirect('resources')

  get :import,to: 'jobs#index',as: :import

  get 'contact-us',to: 'contact#index',as: 'contact_us'

  # resources :articles
  resources :blogs, path: 'articles'
  get 'blog' => redirect('articles')
  get 'category/blog' => redirect('articles')
  get 'blog/*path' => redirect('articles')

  resources :syndications, path: 'track-record'

  get 'api/v1/map.png',to: 'map#index',as: 'map'
  get 'api/v1/map.js',to: 'map#js',as: 'js'
  get '/thank-you',to: 'home#thank_you',as: 'after_contact'

  # ARTICLE LINKS
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  link = 'Our Difference'
  get link.parameterize, to: 'articles#our_difference', as: link.parameterize.underscore

  link = 'FAQ'
  get link.parameterize, to: 'articles#faq', as: link.parameterize.underscore
  get 'faqs' => redirect('faq')

  link = 'Financing Investments'
  get link.parameterize, to: 'articles#financing_investments', as: link.parameterize.underscore

  link = 'Property Management'
  get link.parameterize, to: 'articles#property_management', as: link.parameterize.underscore

  link = 'Market & City Reports'
  get link.parameterize, to: 'articles#market_and_city_reports', as: link.parameterize.underscore
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:

  namespace :api do
    namespace :v1 do

      resources :links
      resources :charts
      resources :jassets

      resources :properties do

        collection do

          put :order,to: 'properties#order'

        end

      end

      resources :testimonies do

        collection do

          put :order,to: 'testimonies#order'

        end

      end

    end
  end

  get 'connect_with_meetup', to: 'events#connect_with_meetup', as: :connect_with_meetup
  get '/oauth2/meetup_api', to: 'oauth2#meetup_api'
  get 'properties-search-results' => redirect('properties')
  get 'my-properties' => redirect('properties')
  get 'MyListings' => redirect('properties')
  get 'PropertyDetails' => redirect('properties')

  post 'api/v1/zendesk/ticket',to: 'zendesk#ticket'
  get 'api/v1/zendesk/articles',to: 'zendesk#articles'

  resources :sessions,path: 'access/normal'
  get 'access/normal',to: 'sessions#index',as: 'login'
  get 'access/logout',to: 'sessions#destroy',as: 'logout'

  resources :users,path: 'our-team'
  put 'api/v1/users/order',to: 'users#order'
  post 'api/v1/mailchimp/signup',to: 'mailchimp#signup'
  post 'api/v1/mailchimp/zendesk',to: 'mailchimp#zendesk'

  resources :events, only: :index
  get 'api/v1/meetup',to: 'events#meetup'
  get 'presentations' => redirect('events')
  get 'wipevents' => redirect('events')
  get 'Dallaspresentation' => redirect('events')
  get 'events/*path' => redirect('events')
  get 'more_events' => 'events#more_events'

  get 'angular',to: 'angular#index'

  get 'youtube',to: 'youtube#index',as: 'youtube'
  get 'youtube/:id',to: 'youtube#show'
  get 'play_video/:videoId' => 'youtube#play_video', as: 'play_video'

  get 'radio-show',to: 'radio_show#index',as: 'radio_show'
  get 'real-estate-radio-live' => redirect('radio-show')
  put 'radio-show',to: 'radio_show#update'

  resources :images
  resources :properties do

    resources :images
    collection do
      get 'get_cities'
      post :import

    end

  end

  root 'home#index'
  get 'cn', to: redirect('http://tomwilsonproperties.sfchinesemedia.com', status: 301)

  if Rails.env.production?
    get '404',to: 'application#page_not_found'
    get '422',to: 'application#change_rejected'
    get '500',to: 'application#server_error'
  end
  get '/sitemap.xml', to: redirect('http://res.cloudinary.com/wilsoninvestments/raw/upload/v1494498777/sitemap.xml', status: 301)
  get '*path' => redirect('/')
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #before_action :set_zendesk

  # def index
  # end
  def show
    @article = @zendesk.GetArticle params[:id]
  end

  def financing_investments
  end

  def our_difference
  end

  def faq
  end

  def property_management
  end

  def market_and_city_reports
  end


  private

  def set_zendesk
    @zendesk = ZendeskApi::Connect.new(
		  domain: ZENDESK_DOMAIN,
		  username: ZENDESK_USER,
		  token: ZENDESK_API_KEY
		)
  end

  def constraints
    params.permit :per_page
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/financing_investments.html.erb
<% set_meta_tags(title: t('seo.financing_investments.title'), description: t('seo.financing_investments.description'), image: asset_url(t('seo.image_1')), twitter: {image: asset_url(t('seo.image_1'))}, og: {image: asset_url(t('seo.image_1'))}) %>
<%= render 'layouts/jumbtron' %>
<section class="main-body without-search-feature">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="box-shadow">
					<ol class="breadcrumb">
						<li><%= link_to 'Home', root_url %></li>
						<li class="active">
							Financing Investments
						</li>
					</ol>
				</div>
			</div>
		</div>
		<div class="row content-section">
			<div class="col-xs-12">
				<h1>Financing Investment in Property</h1>
				<p>
					IRAs, investment loans, hard money loans, &amp; cash.  There are many ways to finance your investment in income producing properties, and Wilson Investment Properties has experts to help you determine what source is best for you.
				</p>
				<h3>IRA</h3>
				<p>
					Self-directed IRAs provide an excellent opportunity to truly diversify your portfolio by <%= link_to 'investing in real estate', root_url, target: '_blank' %>. There are several companies that specialize in providing custodial services for <%= link_to 'real estate investment', root_url, target: '_blank' %>. Some IRA custodians may consider stocks to be the only way to self-direct your retirement income. This is not true! Real estate investing is a legitimate, legal, and excellent way to grow your retirement savings. We currently work with Bill Neville at Entrust <%= mail_to 'bneville@theentrustgroup.com' %>. Call us for a list of knowledgeable IRA custodians.
				</p>
				<h3>Investment Loan</h3>
				<p>
					Many investors purchase with the leverage of an investment loan. The investor supplies the down payment, uses the rental income to make the mortgage payments, and then enjoys the remainder as positive monthly income.  We recommend working with lenders who are experienced with investor loans and lender laws in the state where your investment property is located.  We have lender specialists as part of our team and are happy to provide lender references. Again, contact referrals here (w / non-endorsement). With government (Fannie Mae) loans near all time lows for 30 year fixed rates, Wilson Investment Properties recommends getting all of this cheap money that you can to leverage your returns.
				</p>
				<h3>Hard Money Loan</h3>
				<p>
					Hard money loans, or bridge loans, are loans secured by real property.  They are often short term in length, and commonly used as a source of down payment or to provide a bridge loan until a conventional mortgage is secured.
				</p>
				<h3>Cash</h3>
				<p>
					Payment in full at the time of closing is always an acceptable way to purchase a property! The percentage of return is less than with a leveraged purchase, however, the absolute net cash flow is greater. A cash purchase provides the minimum risk and at the same time the least upside increase in cash flow and value. Wilson Investment Properties recommends utilizing conservative leverage between 60% and 80%.
				</p>
				<h3>Equity Partners</h3>
				<p>
					If you don’t currently qualify for a conventional U.S. loan, you may find an equity partner to carry the loan and while sharing title and equity in the property. This allows one to get invested right away for time-sensitive opportunities.
				</p>
			</div>
		</div>
	</div>
</section>

app/views/articles/index.html.erb
<div ng:controller="ArticlesCtrl">
  <ol class="breadcrumb">
    <li><%= link_to 'Home',root_url %></li>
    <li class="active">Articles</li>
    <% if current_user %>
    <li><%= link_to 'New',"https://tomwilsonproperties.zendesk.com/hc/admin/articles/new",target: '_blank' %></li>
    <% end %>
  </ol>
  <div>
    <h1>Articles</h1>
  </div>
  <hr>
  <h3 ng:if="meta.articles.loading">Loading...</h3>
  <h3 ng:if="!meta.articles.loading && articles.length == 0">No articles found.</h3>
  <div ng:show="!meta.articles.loading" ng:repeat="article in articles">
    <div class="row">
      <div class="col-sm-12">
        <a href="<%= articles_url %>/{{article.id}}"><h3 class="title">{{article.name}}</h3></a>
        <p class="text-muted">Published {{article.raw_created_at}}</p>
      </div>
    </div>
    <hr>
  </div>
</div>

app/views/articles/our_difference.html.erb
<% set_meta_tags(title: t('seo.our_difference.title'), description: t('seo.our_difference.description'), image: asset_url(t('seo.image_2')), twitter: {image: asset_url(t('seo.image_2'))}, og: {image: asset_url(t('seo.image_2'))}) %>
<%= render 'layouts/jumbtron' %>
<section class="main-body without-search-feature">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="box-shadow">
					<ol class="breadcrumb">
						<li>
							<%= link_to 'Home', root_url %>
						</li>
						<li class="active">
							Our Difference
						</li>
					</ol>
				</div>
			</div>
		</div>
		<div class="row content-section">
			<div class="col-xs-12">
				<h1>Our Difference - Success Strategies in Property Investment</h1>
				<h4>The Wilson Investment Properties Difference</h4>
				<p>
					Wilson Investment Properties prides itself as being the premier turnkey provider of investment properties available. We use our decades of experience to maximize your return while selecting high quality properties in strong cities to reduce risk. Our experience has taught us the Big Five strategies for success:
				</p>
				<ol>
					<li>
						<b> Know the Territory</b>
					</li>
					<li>
						<b> Focus on Cash Flow</b>
					</li>
					<li>
						<b> Invest in Quality</b>
					</li>
					<li>
						<b> Leave Nothing to Chance (Turnkey Investments)</b>
					</li>
					<li>
						<b> Keep Business Practices Transparent</b>
					</li>
				</ol>
				<p>
					We put those strategies to work for you. The properties we offer have been hand selected, fully renovated, with property management already in place. We also give you the support and coordination of our entire preferred professional team, the same experienced team that Tom Wilson uses for his personal portfolio. Most new investors do not realize the comprehensive amount of work and knowledge needed to acquire an optimum property and get it to the point where it is cash flowing property. We've done that work for you and it makes a difference!
				</p>
				<h4 class="mar-top-30"><b>Unique Advantages of Wilson Investment Properties</b></h4>
				<ul>
					<li>
						 Experience and success of Wilson Investment Properties' team
					</li>
					<li>
						 Tom Wilson's technical and business background in Silicon Valley, contributing to research of the best cities, properties, and formulas for optimum returns on investments
					</li>
					<li>
						 Wilson Investment Properties is Silicon Valley based, accessible, and understands the needs and perspectives of out of state investors
					</li>
					<li>
						 Facilitates faster path to owning top investment property
					</li>
					<li>
						 Reduces time, hassle, and risk of buying investment property, especially in a new area
					</li>
					<li>
						 More selective and higher quality products for optimum ROI than options available through other sources
					</li>
					<li>
						 Fully rehabbed homes, not just raw foreclosures, or minimally repaired properties for minimal rents
					</li>
					<li>
						 Renter-occupied investment properties
					</li>
					<li>
						 Top experienced and high integrity property management
					</li>
				</ul>
				<p>
					<b>Optimized team of investor lenders, insurance specialists, attorneys, tax specialists, property managers, real estate agents, title company officers, and 1031 exchange accommodators</b>
				</p>
			</div>
		</div>
	</div>
</section>

app/views/articles/property_management.html.erb
<% set_meta_tags(title: t('seo.property_management.title'), description: t('seo.property_management.description'), image: asset_url(t('seo.image_4')), twitter: {image: asset_url(t('seo.image_4'))}, og: {image: asset_url(t('seo.image_4'))}) %>
<%= render 'layouts/jumbtron' %>
<section class="main-body without-search-feature">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="box-shadow">
					<ol class="breadcrumb">
						<li>
							<%= link_to 'Home', root_url %>
						</li>
						<li class="active">
							Property Management
						</li>
					</ol>
				</div>
			</div>
		</div>
		<div class="row content-section">
			<div class="col-xs-12">
				<h1>Property Management Services</h1>
<p>When you purchase an investment property from <%= link_to 'Wilson Investment Properties', root_url, target: '_blank' %>, professional property management is already in place.  At any time, however, you are free to choose a different property manager.</p>

<p>We highly recommend the property managers who also manage our portfolio and have negotiated a reduced rate for our clients. A normal full service* management fee is 10% of <b>collected</b> rent, plus a new lease fee (often 1/2 of a month’s rent). For Wilson investment Properties’ clients, many of our property managers have provided discounted rates.</p>

<p><i>*Full service means that the property manager handles tenant screening,  and leasing, rent collection, insurance, repairs, inspections, accounting, monthly reporting, and deposits of your net income directly into your account.</i></p>
<h3>Property Management Details</h3>
<p>Below are details typically seen in most property management agreements in place on our turnkey properties.</p>
<ol>
<li><b>Cost:</b> Our property managers provide comprehensive services while discounting their fee.</li>
<li><b>Communication:</b>  Property Managers  use email and respond to either telephone or email inquiries. They aim  to return calls to both tenants and investors in the same timely manner, within an hour for non-emergencies and 15 minutes during an emergency.</li>
<li><b>Termination:</b> They  make every effort to provide superior service, so much so that if you do decide to go with another property manager, they  do not charge you fees or penalties for breaking your contract.</li>
<li><b>Repairs and Maintenance:</b>  Property Managers  have relationships with certified contractors in order to respond quickly with the right skill-set for the job.  The maximum they  spend without contacting the investor/client is $300.</li>
<li><b>Monthly Statements:</b>   PMs  provide monthly electronic income & expense statements.  Many  also provide an electronic portal in which you have direct access to their  software and can pull your own set of reports, check to see if your tenant has paid, and check your account balance.  Accounting staff is adept at handling a simple partnership to a detailed LLC and syndications.  Year end statements will be timely.</li>
<li><b>Evictions:</b>   They avoid evictions by placing the right people in the property and then keeping them satisfied.  When someone becomes unable to pay, property managers  offer to waive the tenant penalties for breaking the lease in exchange for leaving the premises without a formal eviction.  If that is not possible, they use an eviction service that understands and complies with state and federal laws.</li>
<li><b>Yard Work:</b> Tenant is responsible for yard maintenance.</li>
<li><b>Reserves:</b>  Property Managers often  require $400 in reserves to cover maintenance and repairs.  When this account is under $100, they ask the investor/client to replenish the account.</li>
<li><b>Vacancies:</b>  They charge up to 1/2 month’s rent to fill vacancies.  These funds cover the cost of advertising, showing the property, running background checks  (checking references, making sure that the tenant is well qualified financially, and that they have been respectful to other landlords), and preparing lease paperwork.</li>
<li><b>Advertising:</b>   Property Managers are experienced in writing effective ads to attract tenants quickly.  They  advertise online, place a sign on the property’s lawn, and  use a showing system whereby tenants may register to see the property from 8 am to 8 pm at night with ease.</li>
<li><b>Section 8:</b> PMs  have experience working with housing programs, qualifying both home and tenants, however most of the <%= link_to 'investment properties', root_url, target: '_blank' %> they  manage do not fit the profile of a section 8 tenant.</li>
</ol>
			</div>
		</div>
	</div>
</section>

app/views/articles/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Home',root_url %></li>
  <li><%= link_to 'Articles',articles_url %>
    <li class="active"><%= @article[:body]['article']['title'] %></li>
    <% if current_user %>
      <li><%= link_to 'Edit',"https://tomwilsonproperties.zendesk.com/hc/admin/articles/#{@article[:body]['article']['id']}/edit",target: '_blank' %></li>
    <% end %>
  </ol>
  <div>
    <h1><%= @article[:body]['article']['title'] %></h1>
  </div>
  <hr>
  <%= @article[:body]['article']['body'].html_safe %>