config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    # NOTE: We want to redirect users to www as the canonical URL in production
    # If you want to test this, you can make hosts entries like:
    # 127.0.0.1       localhost localhost.com www.localhost.com
    # and remove the production conditional
    constraints subdomain: false do
      get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
    end
  end

  resources :meetup_events
  resources :jassets,path: :resources
  get 'market-resources' => redirect('resources')

  get :import,to: 'jobs#index',as: :import

  get 'contact-us',to: 'contact#index',as: 'contact_us'

  # resources :articles
  resources :blogs, path: 'articles'
  get 'blog' => redirect('articles')
  get 'category/blog' => redirect('articles')
  get 'blog/*path' => redirect('articles')

  resources :syndications, path: 'track-record'

  get 'api/v1/map.png',to: 'map#index',as: 'map'
  get 'api/v1/map.js',to: 'map#js',as: 'js'
  get '/thank-you',to: 'home#thank_you',as: 'after_contact'

  # ARTICLE LINKS
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  link = 'Our Difference'
  get link.parameterize, to: 'articles#our_difference', as: link.parameterize.underscore

  link = 'FAQ'
  get link.parameterize, to: 'articles#faq', as: link.parameterize.underscore
  get 'faqs' => redirect('faq')

  link = 'Financing Investments'
  get link.parameterize, to: 'articles#financing_investments', as: link.parameterize.underscore

  link = 'Property Management'
  get link.parameterize, to: 'articles#property_management', as: link.parameterize.underscore

  link = 'Market & City Reports'
  get link.parameterize, to: 'articles#market_and_city_reports', as: link.parameterize.underscore
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
  # :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:

  namespace :api do
    namespace :v1 do

      resources :links
      resources :charts
      resources :jassets

      resources :properties do

        collection do

          put :order,to: 'properties#order'

        end

      end

      resources :testimonies do

        collection do

          put :order,to: 'testimonies#order'

        end

      end

    end
  end

  get 'connect_with_meetup', to: 'events#connect_with_meetup', as: :connect_with_meetup
  get '/oauth2/meetup_api', to: 'oauth2#meetup_api'
  get 'properties-search-results' => redirect('properties')
  get 'my-properties' => redirect('properties')
  get 'MyListings' => redirect('properties')
  get 'PropertyDetails' => redirect('properties')

  post 'api/v1/zendesk/ticket',to: 'zendesk#ticket'
  get 'api/v1/zendesk/articles',to: 'zendesk#articles'

  resources :sessions,path: 'access/normal'
  get 'access/normal',to: 'sessions#index',as: 'login'
  get 'access/logout',to: 'sessions#destroy',as: 'logout'

  resources :users,path: 'our-team'
  put 'api/v1/users/order',to: 'users#order'
  post 'api/v1/mailchimp/signup',to: 'mailchimp#signup'
  post 'api/v1/mailchimp/zendesk',to: 'mailchimp#zendesk'

  resources :events, only: :index
  get 'api/v1/meetup',to: 'events#meetup'
  get 'presentations' => redirect('events')
  get 'wipevents' => redirect('events')
  get 'Dallaspresentation' => redirect('events')
  get 'events/*path' => redirect('events')
  get 'more_events' => 'events#more_events'

  get 'angular',to: 'angular#index'

  get 'youtube',to: 'youtube#index',as: 'youtube'
  get 'youtube/:id',to: 'youtube#show'
  get 'play_video/:videoId' => 'youtube#play_video', as: 'play_video'

  get 'radio-show',to: 'radio_show#index',as: 'radio_show'
  get 'real-estate-radio-live' => redirect('radio-show')
  put 'radio-show',to: 'radio_show#update'

  resources :images
  resources :properties do

    resources :images
    collection do
      get 'get_cities'
      post :import

    end

  end

  root 'home#index'
  get 'cn', to: redirect('http://tomwilsonproperties.sfchinesemedia.com', status: 301)

  if Rails.env.production?
    get '404',to: 'application#page_not_found'
    get '422',to: 'application#change_rejected'
    get '500',to: 'application#server_error'
  end
  get '/sitemap.xml', to: redirect('http://res.cloudinary.com/wilsoninvestments/raw/upload/v1494498777/sitemap.xml', status: 301)
  get '*path' => redirect('/')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  after_action :reset_locale, only: :index_cn
  layout 'thank_you', only: [:thank_you, :login_iframe]

  def index
    @testimonies = Testimony.order(:sort).limit(8)
    properties = Property.active.for_sale_and_reserved.limit(6)
    @properties = Property.order_featured_properties(properties)
    @meetup_event = MeetupEvent.last
    @syndications = Syndication.where(status: ['active', 'currently_held']).order(:status).by_user(current_user).limit(4)
  end

  def thank_you
  end

  def login_iframe
  end

  def index_cn
    I18n.locale = :cn
  end

  private

  def reset_locale
    I18n.locale = :en
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def status_color(status)
    case status
      when 'for_sale'
        'green'
      when 'reserved'
        'yellow'
      else
        'yellow'
    end
  end

  def section_bg_class(properties, section)
    case section
      when 'magazine'
        if properties
          'grey-bg bdr-top-btm'
        else
          'white-bg'
        end
      when 'feedback'
        if properties
          'white-bg'
        else
          'grey-bg bdr-top-btm'
        end
      when 'company-content'
        if properties
          'grey-bg bdr-top-btm'
        else
          'white-bg'
        end
    end
  end
end

app/views/home/_contact_us.html.erb
<div id="home-contact" class="modal fade" role="dialog" ng:controller="TicketCtrl">
  <div class="modal-dialog property-contact-popup">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <uib-alert ng:repeat="alert in alerts" type="{{alert.type}}">{{alert.message}}</uib-alert>
        <h4 class="modal-title"><i class="fa fa-envelope" aria-hidden="true"></i> Contact Us</h4>
      </div>
      <div class="modal-body">
        <form name="ticket_form" ng:submit="submitForm()" class="form-horizontal" novalidate>
          <div class="form-group">
            <div class="col-sm-6 col-xs-12">
              <i class="fa fa-user input-icons" aria-hidden="true"></i>
              <input id="first_name" type="text" class="form-control" ng:model="inquiry.first_name" placeholder="First Name" required>
            </div>
            <div class="col-sm-6 col-xs-12 last-name">
              <i class="fa fa-user input-icons" aria-hidden="true"></i>
              <input id="last_name" type="text" class="form-control" ng:model="inquiry.last_name" placeholder="Last Name" required>
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <i class="fa fa-envelope input-icons" aria-hidden="true"></i>
            <input id="email" type="email" class="form-control" ng:model="inquiry.email" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <i class="fa fa-phone input-icons" aria-hidden="true"></i>
            <input id="phone" type="tel" class="form-control" ng:model="inquiry.phone" placeholder="Phone #" required>
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <i class="fa fa-pencil-square-o input-icons" aria-hidden="true"></i>
            <input id="subject" type="text" class="form-control" ng:model="inquiry.subject" placeholder="A brief description of the inquiry" required>
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <i class="fa fa-pencil-square-o input-icons" aria-hidden="true"></i>
            <textarea id="description" rows="4" class="form-control" ng:model="inquiry.description" placeholder="Please describe the nature of your inquiry" required></textarea>
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12">
              <i class="fa fa-question-circle input-icons" aria-hidden="true"></i>
              <select class="form-control" id="hereUs" ng:model="inquiry.hear_from" ng-options="x for x in inquiry.hear_from_options">
              </select>
            </div>
          </div>
          <div class="form-group btns-row">
            <div class="col-xs-12">
            <div class="checkbox">
              <label>
                <input type="checkbox" ng:model="inquiry.newsletter"><span class="cr"><i class="cr-icon fa fa-check"></i></span> Sign up for our Newsletter
              </label>
            </div>
            <button type="submit" class="btn blue-btn" ng:disabled="!ticket_form.$valid" ng:if="!loading"><i class="fa fa-check" aria-hidden="true"></i> Submit</button>
            <button type="submit" class="btn btn-warning" ng:disabled="true" ng:if="loading"><i class="fa fa-ellipsis-h" aria-hidden="true"></i> Submitting</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/home/index_cn.html.erb
  <% set_meta_tags(title: t('seo.site_title'), image: asset_url(t('seo.image')), twitter: {image: asset_url(t('seo.image'))}, og: {image: asset_url(t('seo.image'))}) %>
<%= render 'layouts/jumbtron' %>
<section class="main-body without-search-feature">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="box-shadow">
          <ol class="breadcrumb">
            <li><%= link_to 'Home', root_url %></li>
            <li class="active">
              Wilson Investment Properties
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="row content-section chinese-content">
      <div class="col-xs-12 text-center mar-top-50 paradise-valley-banner">
        <%= image_tag "paradise-valley-chinese-banner.jpg", alt: 'Paradise Valley, Assisted living, Fairfield, CA', class: "img-responsive" %>
        <div class="mar-top-15">
          <a href="#" data-toggle="modal" data-target="#paradise-home-contact" class="btn border-btn btn-lg"><i class="fa fa-envelope" aria-hidden="true"></i> 联系我们 </a>
        </div>
      </div>
      <div class="col-xs-12 mar-top-30">
        <h1>美国威尔逊物业投资公司</h1>
        <p>美国威尔逊物业投资公司 (Wilson Investment Properties, Inc.) 坐落于加州的硅谷， 是全国首屈-指的物业投资供应商。 威尔逊物业投资公司依据数据指标为精明的投资者提供高回报的一站式 (即可立即入住)、 多业主的住宅，商业及工业物产。 我们积累了几十年的房地产投资经验， 能够最大程度地提高投资回报。 我们通常在物业市场活跃的城市， 如德州的达拉斯， 选择高品质地产， 从而降低风险。</p>
        <div class="row mar-btm-30 mar-top-30">
          <div class="col-sm-5 col-xs-12"><%= image_tag 'chinese_investor_1.jpg', alt: '', class: 'img-responsive' %></div>
          <div class="col-sm-7 col-xs-12 second-img"><%= image_tag 'chinese_investor_2.jpg', alt: '', class: 'img-responsive' %></div>
        </div>
        <h3>汤姆·威尔逊</h3>
        <p>早在70年代， 威尔逊先生就开始建立他个人的房地产投资组合。 开始是兼职， 但在几家著名硅谷半导体公司从事制造和工程管理30年后， 他全职投入房地产投资业务， 并充分利用他在工业界所积累的业务和管理经验， 投资回报斐然。 迄今为止他一共购买并销售了超过3500套房地产和物业， 总价值超过2.5亿美元， 其中包括3个公寓改造项目， 9个众筹物业投资和8个公寓式房产。 他创立并拥有威尔逊物业投资公司 (Wilson Investment Properties)， 该公司向投资者提供了500多个高现金流， 高质量， 重新装修后再租赁的住宅物业。 他在房地产协会中非常活跃， 在房地产投资俱乐部的活动中经常进行主题演讲， 威尔逊先生的坦率和才能使他成为听众的最爱。 作为推广工作的一部分， 他经常为新投资者提供指导。 他每周都在旧金山湾区的房地产广播节目中向听众提供深度的房地产投资教育信息。</p>
        <h3>美国威尔逊物业投资公司的 5大成功策略 ：</h3>
        <ul>
          <li>充分了解房地产投资的地域情况</li>
          <li>非常关注现金流</li>
          <li>只投资高质量的房地产物业</li>
          <li>注重将房地产投资风险降到最低</li>
          <li>始终对客户保持业务实践的透明度</li>
        </ul>
        <p>一站式房屋租赁</p>
        <p>国际投资者特别喜欢威尔逊物业投资公司， 因为我们提供真正的一站式 (即可立即入住) 产品。 我们的高质量投资房屋建成时间都不早于 1980年代，  并且都位于高就业和经济活跃的地区。 这些物业都是新近装修的， 其租赁和物业管理都已经到位。 即使有些投资者愿意管理自己的财产， 我们也向他们提供这样的选择。 为了得到良好的现金流， 月租金应该接近于总投资金额的 1％。 达拉斯是我们最喜欢的市场， 它是全国经济最为活跃的经济体之一， 其房地产的价格仍然较低， 而且投资回报率比较高。 许多投资者从独立的家庭住宅开始， 因为这些房地产的价值容易估算， 流动性也比较好。  我们的这些投资项目都得到我们知识渊博的团队的全力支持， 服务非常到位。</p>
        <p><%= link_to '[点击这里查看所有优惠项目]', properties_path %></p>
        <div class="row mar-top-15">
          <div class="col-md-6 col-sm-7 col-xs-12">
            <iframe width="1366" height="768" src="https://www.youtube.com/embed/jBgYZzwjTak" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
        <h3>多业主住宅及商业众筹</h3>
        <p>商业众筹物产企业汇集来自多个投资者的资金， 用于共同的投资目标。 我们使用这些资金收购大型商业、 多单元住宅楼、 零售商铺和工业物业， 具有如下特点 :</p>
        <ul>
          <li>投资的年股息为 8-10%， 来自于租金收入， 每个季度都有一次分红</li>
          <li>物业持有期为三至七年</li>
          <li>交易退出时利润共享</li>
          <li>平均年度回报率为 17-25％</li>
        </ul>
        <p>这些物产投资的优点包括 ：</p>
        <ul>
          <li>多元化的资产类别</li>
          <li>完全的被动式投资</li>
          <li>更好的谈判结果</li>
          <li>更好的贷款</li>
          <li>只需5万美元就可参与购买更大更高质量的房产</li>
          <li>专业管理， 真正的一站式可立即入住物产</li>
          <li>使客户更容易进入不熟悉的市场</li>
          <li>责任仅限于投资的金额</li>
        </ul>
        <p>根据美国证券交易委员会的法律， 我们的众筹物产只能提供给我们自己的关系客户。</p>
        <p><%= link_to '[注册加入我们的客户网络并开始接收独家的优惠信息]', contact_us_path, method: :get %></a></p>
        <div class="row mar-top-15 mar-btm-15">
          <div class="col-md-6 col-sm-7 col-xs-12">
            <iframe width="1366" height="768" src="https://www.youtube.com/embed/v37TGqQd9yk" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
        <p><b>** 注意： 必须持有美国的纳税人税号， 才能成为我们的投资客户。</b></p>
      </div>
    </div>
  </div>
</section>
<%= render 'contact_us' %>

app/views/home/login_iframe.html.erb
<div class="iframe-container">
  <iframe src="https://thomaswilsonproperties.evesttech.net/investor/login" width='100%' height='100%'>
  </iframe>
</div>

app/views/home/thank_you.html.erb
<div class="mainContainer">
  <div class="container">
    <h2 class="thank-you">Thank You! <span>Your response was successfully submitted</span></h2>
  </div>
</div>